#Actividad R1-A1-S1 Redes Neuronales básicas
###Estudiante:
###Medin Alejandro Pinto Ardila



>


Objetivos:
* Comprender los conceptos fundamentales de Machine Learning y Deep Learning.
*   Identificar el funcionamiento del perceptrón y las redes neuronales artificiales.
* Reconocer las diferencias entre redes neuronales de una capa y multicapa.
* Comprender la importancia de la vectorización en el procesamiento de datos.
* Comprender la importancia de la vectorización en el procesamiento de datos.
* Identificar el uso de Numpy para operaciones matemáticas aplicadas a redes neuronales.
* Reconocer el funcionamiento básico de modelos neuronales sin uso de librerías especializadas.


In [2]:
#Programación de perceptrón.
# Importamos NumPy para trabajar con vectores, matrices y operaciones numéricas.
import numpy as np

# Definimos las entradas de un ejemplo.
# Cada valor representa una característica del caso.
X = np.array([0.8, 0.6, 0.7])

# Definimos un peso para cada entrada.
# El peso determina la influencia de cada característica.
W = np.array([0.5, 0.3, 0.2])

# Definimos el sesgo o bias.
b = 0.0

# Calculamos la suma ponderada de las entradas.
# Se multiplica cada entrada por su peso y luego se suman los resultados.
z = np.dot(X, W) + b

# Definimos una función de activación
# Si z es mayor o igual a cero, devuelve 1.
# Si z es menor que cero, devuelve 0.
def funcion_activacion(z):
    return 1 if z >= 0 else 0

# Aplicamos la función de activación al resultado obtenido.
prediccion = funcion_activacion(z)

# Mostramos el resultado antes de la activación.
print("Resultado ponderado:", z)

# Mostramos la predicción final del perceptrón.
print("Predicción:", prediccion)

Resultado ponderado: 0.7200000000000001
Predicción: 1


In [5]:
#Programación de red neuronal de una capa.
# Importamos NumPy.
import numpy as np

# Definimos 4 casos con 3 características de entrada.
X = np.array([
    [0.8, 0.6, 0.7],
    [0.2, 0.3, 0.1],
    [0.9, 0.8, 0.7],
    [0.1, 0.2, 0.3]
])

# Definimos una matriz de pesos.
# Cada columna representa una neurona de la capa.
# Tenemos 3 entradas y 3 neuronas.
W1 = np.array([
    [0.5, 0.2, 0.1],
    [0.3, 0.4, 0.2],
    [0.2, 0.1, 0.6]
])

# Definimos un sesgo para cada neurona.
b1 = np.array([-0.5, 0.1, 0.2])

# Calculamos la combinación ponderada de las entradas.
Z1 = X @ W1 + b1

# Implementamos ReLU.
# Los valores negativos se convierten en 0.
# Los valores positivos permanecen sin cambio.
A1 = np.maximum(0, Z1)

# Mostramos el resultado antes de la activación.
print("Z1:")
print(Z1)

# Mostramos la salida de la capa.
print("A1:")
print(A1)

Z1:
[[ 0.22  0.57  0.82]
 [-0.29  0.27  0.34]
 [ 0.33  0.67  0.87]
 [-0.33  0.23  0.43]]
A1:
[[0.22 0.57 0.82]
 [0.   0.27 0.34]
 [0.33 0.67 0.87]
 [0.   0.23 0.43]]


In [6]:
#Programación de red neuronal multicapa (Vainilla).
# Importamos NumPy.
import numpy as np

# ---------------------------------------------------------
# 1. DATOS DE ENTRADA
# ---------------------------------------------------------

# Creamos 4 casos con 3 características cada uno.
X = np.array([
    [0.8, 0.6, 0.7],
    [0.2, 0.3, 0.1],
    [0.9, 0.8, 0.7],
    [0.1, 0.2, 0.3]
])

# ---------------------------------------------------------
# 2. PRIMERA CAPA
# ---------------------------------------------------------

# Definimos los pesos de la primera capa.
# Hay 3 entradas y 3 neuronas.
W1 = np.array([
    [0.5, 0.2, 0.1],
    [0.3, 0.4, 0.2],
    [0.2, 0.1, 0.6]
])

# Definimos un sesgo para las 3 neuronas.
b1 = np.array([-0.5, 0.1, 0.2])

# Calculamos la salida lineal de la primera capa.
Z1 = X @ W1 + b1

# Aplicamos ReLU.
A1 = np.maximum(0, Z1)

# ---------------------------------------------------------
# 3. SEGUNDA CAPA
# ---------------------------------------------------------

# La segunda capa recibe las 3 salidas de la primera capa.
# Por eso W2 tiene 3 filas y 1 columna.
W2 = np.array([
    [0.4],
    [0.5],
    [0.3]
])

# Definimos el sesgo de la segunda capa.
b2 = 0.0

# Calculamos la salida lineal de la segunda capa.
Z2 = A1 @ W2 + b2

# ---------------------------------------------------------
# 4. FUNCIÓN SIGMOIDE
# ---------------------------------------------------------

# Definimos la función sigmoide.
def sigmoide(z):
    return 1 / (1 + np.exp(-z))

# Aplicamos la sigmoide a la salida de la segunda capa.
A2 = sigmoide(Z2)

# ---------------------------------------------------------
# 5. PREDICCIÓN
# ---------------------------------------------------------

# Convertimos la salida entre 0 y 1 en una decisión binaria.
# Si es mayor o igual a 0.5, clasificamos como 1.
predicciones = np.where(A2 >= 0.5, 1, 0)

# ---------------------------------------------------------
# 6. RESULTADOS
# ---------------------------------------------------------

# Mostramos los resultados intermedios.
print("Salida de la primera capa (A1):")
print(A1)

print("\nSalida de la segunda capa (Z2):")
print(Z2)

print("\nSalida sigmoide (A2):")
print(A2)

print("\nPredicciones:")
print(predicciones)

Salida de la primera capa (A1):
[[0.22 0.57 0.82]
 [0.   0.27 0.34]
 [0.33 0.67 0.87]
 [0.   0.23 0.43]]

Salida de la segunda capa (Z2):
[[0.619]
 [0.237]
 [0.728]
 [0.244]]

Salida sigmoide (A2):
[[0.64999108]
 [0.55897421]
 [0.67436623]
 [0.56069915]]

Predicciones:
[[1]
 [1]
 [1]
 [1]]


####Enlace funcional al repositorio de gibhub: https://github.com/2Alejo0/DeepLearning